In [1]:
import numpy as np
import time

In [2]:
# Vector creation
# Numpy routines which allocate memory and fill arrays with value
a = np.zeros(4);  print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4) :   a = [0.39849243 0.15244795 0.74837646 0.70746633], a shape = (4,), a data type = float64


In [4]:
# Numpy routines which allocate memory and fill arrays with value but do not as input argument
a = np.arange(4); print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4); print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0 1 2 3], a shape = (4,), a data type = int32
np.random.rand(4): a = [0.50281227 0.77542765 0.17052701 0.86096002], a shape = (4,), a data type = float64


In [6]:
a = np.array([5, 4, 3, 2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5., 4, 3, 2]);  print(f"np.array([5.,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]):  a = [5. 4. 3. 2.],     a shape = (4,), a data type = float64


In [11]:
# Indexing
# Vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

# access an element
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexes must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


$Slicing$

- slicing creates an array of indices using a set of three values (start: end: step)

In [20]:
# Vector slicing operation
a = np.arange(10)
print(f"a  = {a}")

# access 5 consecutive elements
c = a[2:7:1]; print(f"c = a[2:7:1] : {c}")

# access 3 elements seprated by two
c = a[2:7:2]; print(f"c = a[2:7:2] : {c}")

# access all elements index 3 and above
c = a[3::1]; print(f"c = a[2::1] : {c}")

# accesss all elements index 3 and below
c = a[:3:1]; print(f"c = a[:3:1] : {c}")

# access all the elements
c = a[:]; print(f"c[:] = {c}")

a  = [0 1 2 3 4 5 6 7 8 9]
c = a[2:7:1] : [2 3 4 5 6]
c = a[2:7:2] : [2 4 6]
c = a[2::1] : [3 4 5 6 7 8 9]
c = a[:3:1] : [0 1 2]
c[:] = [0 1 2 3 4 5 6 7 8 9]


#### Single vector operations

In [26]:

a = np.array([1, 2, 3, 4])

# negate elements of a
b = -a
print(f"b = -a : {b}")

# sum all elements of a , returns a scalar
b = np.sum(a)
print(b)

b = np.mean(a)
print(b)

b = a**2
print(b)

b = -a : [-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


#### vector vector element-wise operations

In [30]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")


# try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)
    

Binary operators work element wise: [0 0 6 8]
The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


#### Scalar vector operations

In [33]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = a * 5
print(b)

[ 5 10 15 20]


#### Vector dot product

In [35]:
def my_dot(a, b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a,b) = {my_dot(a, b)}")


# same operation with np.dot
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"Numpy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape}")
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

my_dot(a,b) = 24
Numpy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = ()
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [36]:
# time difference between vector and loop
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 68.5651 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2848.9137 ms 


$Metrices$

In [38]:
# Matrix creation
a = np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2,1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1,1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.04997798]]


In [41]:
# Numpy routines which allocate memory and fill user specified values
a = np.array([[5], [4], [3]]);  print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


## Operation on matrices

#### Indexing

In [51]:
a = np.arange(6).reshape(-1, 2) # reshape is a conveniant way to create matrix
print(f"a.shape: {a.shape}, \na={a}")

# access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

# access a row
print(f"a[2].shape : {a[2].shape} \n a[2] : {a[2]}")

a.shape: (3, 2), 
a=[[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape : (2,) 
 a[2] : [4 5]


In [53]:
# Slicing
# Vector 2-D slicing operation
a = np.arange(20).reshape(-1, 10)
print(f"a = {a}")

# access 5 consecutive elements
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

# access 5 consec

a = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
